### ISSUE TITLE
proposed-revisions/webfolio

### ISSUE THREAD

**Issue by radhtkamal** [rey-dan/webfolio#1]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/96300264/215430729-fc1ab95f-f342-486e-afd6-4b9e5a0cdf28.png">
Remove horizontal scroll by adding the following properties to `main`: 
`{ overflow-x: hidden; }`

<img width="750" alt="image" src="https://user-images.githubusercontent.com/96300264/215431242-bddebf11-db29-4fe5-93c8-c99cf5ef2a8b.png">
Remove  `overflow-y: scroll`  from `main`, double scrollbar appears because of this.
Set `{ margin-left: 340px }` to main instead.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/96300264/215435896-90cbfcee-17ec-45a2-908c-409accb8bd56.png">
Add the following properties to `nav`:
 `{ height: 100vh;
    position: fixed; }`
Remove position: static

**Comment by rey-dan** [comment]
Done with the latest update. Thanks
